补丁包
====

我在分支fix-chinese-name上做了2处修改，分别打了2个tag。

  * 1.5.2.2: 修复了windows系统上中文用户名导致RIDE运行失败的问题，可以去release里下载。
  * 1.5.2.3: 修复了之前UnicodeDecodeError的报错，此tag包含前一个tag的修改内容

如果要看代码改动，请自己查看最近提交的代码，如想要安装：请自己下载对应的安装包（假设文件名是RIDE.zip），然后执行：

    pip install RIDE.zip

RIDE
====

RIDE is a development environment for Robot Framework test cases.

*NEW* Join RIDE discussion in Robot Framework Slack: https://robotframework.slack.com
(signup page: https://robotframework-slack.herokuapp.com)

  * Downloads_
  * Usage instructions and some tips and tricks can be found from the Wiki_
  * Bug report/enhancement request? Use the `issue tracker`_.
  * Any questions? Do not hesitate to use the `mailing list`_.
  * Development information is in `BUILD`_ file.

Installation
============

.. image:: http://img.youtube.com/vi/zpenQJcrBNg/sddefault.jpg
   :target: https://www.youtube.com/watch?feature=player_embedded&v=zpenQJcrBNg

A very simple demo
==================

.. image:: http://img.youtube.com/vi/6F_xGKdoN1E/sddefault.jpg
   :target: https://www.youtube.com/watch?feature=player_embedded&v=6F_xGKdoN1E

.. _Downloads: https://pypi.python.org/pypi/robotframework-ride
.. _Wiki: https://github.com/robotframework/RIDE/wiki
.. _issue tracker: https://github.com/robotframework/RIDE/issues
.. _BUILD: https://github.com/robotframework/RIDE/blob/master/BUILD.rest
.. _mailing list: http://groups.google.com/group/robotframework-users/
